(cl:defpackage way_point_wamv-srv
  (:use )
  (:export
   "ADD_WAY_POINT"
   "<ADD_WAY_POINT-REQUEST>"
   "ADD_WAY_POINT-REQUEST"
   "<ADD_WAY_POINT-RESPONSE>"
   "ADD_WAY_POINT-RESPONSE"
   "WAY_POINT_CMD"
   "<WAY_POINT_CMD-REQUEST>"
   "WAY_POINT_CMD-REQUEST"
   "<WAY_POINT_CMD-RESPONSE>"
   "WAY_POINT_CMD-RESPONSE"
  ))

