// Generated by gencpp from file way_point_wamv/add_way_pointResponse.msg
// DO NOT EDIT!


#ifndef WAY_POINT_WAMV_MESSAGE_ADD_WAY_POINTRESPONSE_H
#define WAY_POINT_WAMV_MESSAGE_ADD_WAY_POINTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace way_point_wamv
{
template <class ContainerAllocator>
struct add_way_pointResponse_
{
  typedef add_way_pointResponse_<ContainerAllocator> Type;

  add_way_pointResponse_()
    : recieved(false)  {
    }
  add_way_pointResponse_(const ContainerAllocator& _alloc)
    : recieved(false)  {
  (void)_alloc;
    }



   typedef uint8_t _recieved_type;
  _recieved_type recieved;





  typedef boost::shared_ptr< ::way_point_wamv::add_way_pointResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::way_point_wamv::add_way_pointResponse_<ContainerAllocator> const> ConstPtr;

}; // struct add_way_pointResponse_

typedef ::way_point_wamv::add_way_pointResponse_<std::allocator<void> > add_way_pointResponse;

typedef boost::shared_ptr< ::way_point_wamv::add_way_pointResponse > add_way_pointResponsePtr;
typedef boost::shared_ptr< ::way_point_wamv::add_way_pointResponse const> add_way_pointResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::way_point_wamv::add_way_pointResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::way_point_wamv::add_way_pointResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace way_point_wamv

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::way_point_wamv::add_way_pointResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::way_point_wamv::add_way_pointResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::way_point_wamv::add_way_pointResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::way_point_wamv::add_way_pointResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::way_point_wamv::add_way_pointResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::way_point_wamv::add_way_pointResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::way_point_wamv::add_way_pointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7dab0b7be2e21c7e76041e8de101b25f";
  }

  static const char* value(const ::way_point_wamv::add_way_pointResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7dab0b7be2e21c7eULL;
  static const uint64_t static_value2 = 0x76041e8de101b25fULL;
};

template<class ContainerAllocator>
struct DataType< ::way_point_wamv::add_way_pointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "way_point_wamv/add_way_pointResponse";
  }

  static const char* value(const ::way_point_wamv::add_way_pointResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::way_point_wamv::add_way_pointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool recieved\n"
"\n"
;
  }

  static const char* value(const ::way_point_wamv::add_way_pointResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::way_point_wamv::add_way_pointResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.recieved);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct add_way_pointResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::way_point_wamv::add_way_pointResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::way_point_wamv::add_way_pointResponse_<ContainerAllocator>& v)
  {
    s << indent << "recieved: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.recieved);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WAY_POINT_WAMV_MESSAGE_ADD_WAY_POINTRESPONSE_H
