// Generated by gencpp from file way_point_wamv/add_way_pointRequest.msg
// DO NOT EDIT!


#ifndef WAY_POINT_WAMV_MESSAGE_ADD_WAY_POINTREQUEST_H
#define WAY_POINT_WAMV_MESSAGE_ADD_WAY_POINTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace way_point_wamv
{
template <class ContainerAllocator>
struct add_way_pointRequest_
{
  typedef add_way_pointRequest_<ContainerAllocator> Type;

  add_way_pointRequest_()
    : latitude(0.0)
    , longitude(0.0)
    , minutes(0.0)  {
    }
  add_way_pointRequest_(const ContainerAllocator& _alloc)
    : latitude(0.0)
    , longitude(0.0)
    , minutes(0.0)  {
  (void)_alloc;
    }



   typedef double _latitude_type;
  _latitude_type latitude;

   typedef double _longitude_type;
  _longitude_type longitude;

   typedef double _minutes_type;
  _minutes_type minutes;





  typedef boost::shared_ptr< ::way_point_wamv::add_way_pointRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::way_point_wamv::add_way_pointRequest_<ContainerAllocator> const> ConstPtr;

}; // struct add_way_pointRequest_

typedef ::way_point_wamv::add_way_pointRequest_<std::allocator<void> > add_way_pointRequest;

typedef boost::shared_ptr< ::way_point_wamv::add_way_pointRequest > add_way_pointRequestPtr;
typedef boost::shared_ptr< ::way_point_wamv::add_way_pointRequest const> add_way_pointRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::way_point_wamv::add_way_pointRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::way_point_wamv::add_way_pointRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace way_point_wamv

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::way_point_wamv::add_way_pointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::way_point_wamv::add_way_pointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::way_point_wamv::add_way_pointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::way_point_wamv::add_way_pointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::way_point_wamv::add_way_pointRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::way_point_wamv::add_way_pointRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::way_point_wamv::add_way_pointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d43d2876a206169446576ec6e7d81660";
  }

  static const char* value(const ::way_point_wamv::add_way_pointRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd43d2876a2061694ULL;
  static const uint64_t static_value2 = 0x46576ec6e7d81660ULL;
};

template<class ContainerAllocator>
struct DataType< ::way_point_wamv::add_way_pointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "way_point_wamv/add_way_pointRequest";
  }

  static const char* value(const ::way_point_wamv::add_way_pointRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::way_point_wamv::add_way_pointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 latitude\n"
"float64 longitude\n"
"float64 minutes\n"
;
  }

  static const char* value(const ::way_point_wamv::add_way_pointRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::way_point_wamv::add_way_pointRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.latitude);
      stream.next(m.longitude);
      stream.next(m.minutes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct add_way_pointRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::way_point_wamv::add_way_pointRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::way_point_wamv::add_way_pointRequest_<ContainerAllocator>& v)
  {
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    s << indent << "minutes: ";
    Printer<double>::stream(s, indent + "  ", v.minutes);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WAY_POINT_WAMV_MESSAGE_ADD_WAY_POINTREQUEST_H
