// Generated by gencpp from file way_point_wamv/way_point_cmdRequest.msg
// DO NOT EDIT!


#ifndef WAY_POINT_WAMV_MESSAGE_WAY_POINT_CMDREQUEST_H
#define WAY_POINT_WAMV_MESSAGE_WAY_POINT_CMDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace way_point_wamv
{
template <class ContainerAllocator>
struct way_point_cmdRequest_
{
  typedef way_point_cmdRequest_<ContainerAllocator> Type;

  way_point_cmdRequest_()
    : command()  {
    }
  way_point_cmdRequest_(const ContainerAllocator& _alloc)
    : command(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _command_type;
  _command_type command;





  typedef boost::shared_ptr< ::way_point_wamv::way_point_cmdRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::way_point_wamv::way_point_cmdRequest_<ContainerAllocator> const> ConstPtr;

}; // struct way_point_cmdRequest_

typedef ::way_point_wamv::way_point_cmdRequest_<std::allocator<void> > way_point_cmdRequest;

typedef boost::shared_ptr< ::way_point_wamv::way_point_cmdRequest > way_point_cmdRequestPtr;
typedef boost::shared_ptr< ::way_point_wamv::way_point_cmdRequest const> way_point_cmdRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::way_point_wamv::way_point_cmdRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::way_point_wamv::way_point_cmdRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace way_point_wamv

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::way_point_wamv::way_point_cmdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::way_point_wamv::way_point_cmdRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::way_point_wamv::way_point_cmdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::way_point_wamv::way_point_cmdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::way_point_wamv::way_point_cmdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::way_point_wamv::way_point_cmdRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::way_point_wamv::way_point_cmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cba5e21e920a3a2b7b375cb65b64cdea";
  }

  static const char* value(const ::way_point_wamv::way_point_cmdRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcba5e21e920a3a2bULL;
  static const uint64_t static_value2 = 0x7b375cb65b64cdeaULL;
};

template<class ContainerAllocator>
struct DataType< ::way_point_wamv::way_point_cmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "way_point_wamv/way_point_cmdRequest";
  }

  static const char* value(const ::way_point_wamv::way_point_cmdRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::way_point_wamv::way_point_cmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string command\n"
;
  }

  static const char* value(const ::way_point_wamv::way_point_cmdRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::way_point_wamv::way_point_cmdRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct way_point_cmdRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::way_point_wamv::way_point_cmdRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::way_point_wamv::way_point_cmdRequest_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WAY_POINT_WAMV_MESSAGE_WAY_POINT_CMDREQUEST_H
