// Generated by gencpp from file robotx_gazebo/UsvDrive.msg
// DO NOT EDIT!


#ifndef ROBOTX_GAZEBO_MESSAGE_USVDRIVE_H
#define ROBOTX_GAZEBO_MESSAGE_USVDRIVE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robotx_gazebo
{
template <class ContainerAllocator>
struct UsvDrive_
{
  typedef UsvDrive_<ContainerAllocator> Type;

  UsvDrive_()
    : left(0.0)
    , right(0.0)  {
    }
  UsvDrive_(const ContainerAllocator& _alloc)
    : left(0.0)
    , right(0.0)  {
  (void)_alloc;
    }



   typedef float _left_type;
  _left_type left;

   typedef float _right_type;
  _right_type right;




  typedef boost::shared_ptr< ::robotx_gazebo::UsvDrive_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotx_gazebo::UsvDrive_<ContainerAllocator> const> ConstPtr;

}; // struct UsvDrive_

typedef ::robotx_gazebo::UsvDrive_<std::allocator<void> > UsvDrive;

typedef boost::shared_ptr< ::robotx_gazebo::UsvDrive > UsvDrivePtr;
typedef boost::shared_ptr< ::robotx_gazebo::UsvDrive const> UsvDriveConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotx_gazebo::UsvDrive_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotx_gazebo::UsvDrive_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robotx_gazebo

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'robotx_gazebo': ['/home/rip-acer-vn7-591g-1/vmrc_ws/src/robotx_gazebo/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robotx_gazebo::UsvDrive_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotx_gazebo::UsvDrive_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotx_gazebo::UsvDrive_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotx_gazebo::UsvDrive_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotx_gazebo::UsvDrive_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotx_gazebo::UsvDrive_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotx_gazebo::UsvDrive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a927990ab5d5c3d628e2d52b8533e52";
  }

  static const char* value(const ::robotx_gazebo::UsvDrive_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a927990ab5d5c3dULL;
  static const uint64_t static_value2 = 0x628e2d52b8533e52ULL;
};

template<class ContainerAllocator>
struct DataType< ::robotx_gazebo::UsvDrive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotx_gazebo/UsvDrive";
  }

  static const char* value(const ::robotx_gazebo::UsvDrive_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotx_gazebo::UsvDrive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Standard USV thrust massage - port and starbard\n\
\n\
# Thrust command - typically ranges from {-1.0 - 1.0}\n\
float32 left\n\
float32 right\n\
";
  }

  static const char* value(const ::robotx_gazebo::UsvDrive_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotx_gazebo::UsvDrive_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left);
      stream.next(m.right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UsvDrive_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotx_gazebo::UsvDrive_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotx_gazebo::UsvDrive_<ContainerAllocator>& v)
  {
    s << indent << "left: ";
    Printer<float>::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    Printer<float>::stream(s, indent + "  ", v.right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTX_GAZEBO_MESSAGE_USVDRIVE_H
